### ISSUE TITLE
Icons smaller than JUMBO are cropped.

### ISSUE THREAD

**Issue by TX256** [MrMarnic/JIconExtract#1] opened 2018-10-01 09:28 UTC
For me, on Windows 10, icons smaller than JUMBO are cropped a bit from right and bottom.

**Comment by MrMarnic** [comment] 2018-10-05 12:47
The issue is known and I am working on it but I cannot tell you an specific date

**Comment by MrMarnic** [comment] 2019-11-08 19:01
Sorry for the big delay. But I managed it only now to fix this problem.
It is fixed in the new project https://github.com/MrMarnic/JIconExtractReloaded.

**Closed as completed** 2019-11-08 19:04 UTC
